name: tutorials_env
channels:
  - defaults
dependencies:
  - python>3.7
  - click=7.1.2
  - ipywidgets=7.6.3
  - jinja2<3.1
  - sphinx=3.5.4
  - sphinx-gallery 
  - renku-sphinx-theme
  - pillow 
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - xarray
  - h5netcdf
  - cartopy>0.21 
  - geopandas
  - eodag>2.9.0
