name: tutorials_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.7
  - click=7.1.2
  - ipywidgets=7.6.3
  - jinja2<3.1
  - sphinx=3.5.4
  - sphinx-gallery 
  - pydata-sphinx-theme
  - pillow 
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - xarray
  - h5netcdf
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
