name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v3
        with:
            fetch-depth: 2
      - name: Install pip dependencies
        run: |
          pip install sphinx sphinx_rtd_theme sphinx-gallery pillow 
      - name: Setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          activate-environment: gh-doc
          environment-file: doc/environment.yml
          miniforge-variant: Mambaforge
      - name: List dependencies
        run: |
          conda list
      - uses: actions/setup-python@v3
      - name: Sphinx build
        run: |
          sphinx-build doc doc/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/_build/
          force_orphan: true
